/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Aplikasi;
import javax.swing.*;
        import java.sql.*;
        import javax.swing.table.*;
        import java.awt.Dimension;
        import java.awt.Toolkit;
/**
 *
 * @author Cab Priok
 */
public class FormMenuu extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    public FormMenuu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tbbooking = new javax.swing.JButton();
        tbjadwal = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        tbprofile = new javax.swing.JButton();
        tblogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("SELAMAT DATANG DI APLIKASI BOOKING LAPANGAN FUTSAL");

        tbbooking.setText("BOOKING NOW");
        tbbooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbbookingActionPerformed(evt);
            }
        });

        tbjadwal.setText("JADWAL LAPANGAN");
        tbjadwal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbjadwalActionPerformed(evt);
            }
        });

        jButton3.setText("PEMBAYARAN");

        tbprofile.setText("PROFIL LAPANGAN");
        tbprofile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbprofileActionPerformed(evt);
            }
        });

        tblogout.setText("log out");
        tblogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(tbbooking))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(jButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tbprofile)
                            .addComponent(tbjadwal)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tblogout)
                            .addComponent(jLabel1))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(45, 45, 45)
                .addComponent(tbbooking)
                .addGap(35, 35, 35)
                .addComponent(tbjadwal)
                .addGap(34, 34, 34)
                .addComponent(jButton3)
                .addGap(31, 31, 31)
                .addComponent(tbprofile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(tblogout)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbbookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbbookingActionPerformed
        // TODO add your handling code here:
new Frame_booking_lapangan().setVisible(true);
 dispose();
    
    }//GEN-LAST:event_tbbookingActionPerformed

    private void tblogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblogoutActionPerformed
        // TODO add your handling code here:
        new FormLogin().setVisible(true);
 dispose();
    }//GEN-LAST:event_tblogoutActionPerformed

    private void tbprofileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbprofileActionPerformed
        // TODO add your handling code here:
        new FormLapangan().setVisible(true);
 dispose();
    }//GEN-LAST:event_tbprofileActionPerformed

    private void tbjadwalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbjadwalActionPerformed
        // TODO add your handling code here:
        new FormJadwal().setVisible(true);
 dispose();
    }//GEN-LAST:event_tbjadwalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMenuu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMenuu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMenuu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMenuu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMenuu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton tbbooking;
    private javax.swing.JButton tbjadwal;
    private javax.swing.JButton tblogout;
    private javax.swing.JButton tbprofile;
    // End of variables declaration//GEN-END:variables
}
